### ISSUE TITLE
resolve export/import issues building web application with create-react-app build

### ISSUE THREAD

**Issue by craigmcchesney** [craigmcchesney/datastore-web-app#66]

**Comment by craigmcchesney** [comment]
### Summary
To summarize, I think the key issue I encountered was that the create-react-app build script treated the input files as ES6.  It complained that they contained assignment to "module.exports", so I removed that.  Then I added "export default" on the class declaration for all my domain classes.  Then there were problems in the files where these exports were imported, because I was using incompatible "require" syntax instead of "import".
### Details
I tested deployment of the datastore web application via the Webpack development server.  This is the simplest way to deploy the application, as it is part of the "create-react-app" framework and is simply initiated via "npm start".  It is probably not suitable for a production deployment (but it might be?), so I'm going to try building the application and deploying via the "server" static file server.  As a follow on task, I'll build a simple node.js server to deploy the static application, as this is probably ultimately what we want to do in production, as I can envision wanting to add other server-side functionality and API.

I'm going to create a production build of the app using npm (link 1), then install the "serve" static file server (links 2,3) and test deploying the web application using that server (link 2):

- sudo su data
- cd ~/datastore-web-app
- npm run build
create production build of application in "build" directory

This fails with the message "Attempted import error: './domain/grpc-client/DatastoreApi' does not contain a default export (imported as 'DatastoreApi').".  It sounds like I am missing an export statement somewhere in that file.  I need to investigate a bit further…

It looks like I need to add an "export default" to the declaration of DatastoreApi, apparently due to how that class is imported elsewhere (links 4, 5, 6).  E.g., App.js imports it as "import DatastoreApi from "./domain/grpc-client/DatastoreApi";", which appears to require "export default".  I'm going to try editing the declaration of DatastoreApi in src/domain/grpc-client/DatastoreApi.js so it looks like this: "export default class DatastoreApi":

- npm run build

Now I get the same error, but for a different class, "QueryFilter".  So I'll make the same change there.  I'm guessing all my javascript classes will have this issue.  Apparently the syntax I used for declaring the domain classes was not ES6, or maybe Webstorm decided to add import statements using the wrong syntax (it added all the imports automatically).  So let me work through occurrences of the error, including:

- src/domain/filter/QueryFilter.js
- src/domain/Constants.js

OK no more build errors after fixing those (there are some lint warnings to clean up).  I'm going to try installing "serve" and using it to serve the application:

- sudo npm install -g serve
- serve -s build

This fails because "serve" is not in my search path.  It seems the solution (link 7) is to set the "NODE_PATH" environment variable to the global node modules directory using:

- export NODE_PATH=$(npm root --quiet -g)

This also did not solve the problem.  According to (link 8), I need to add the npm "prefix" bin directory (/usr/local/bin) to my PATH.  I added it to .bashrc using:

- echo "export PATH=$PATH:$(npm get prefix)/bin" >> ~/.bashrc

And then run the command directly to update PATH variable in current session:

- export PATH=/home/data/.local/bin:/home/data/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin

Now the "serve" command is found in the PATH.  So now to try running the server:

- serve -s build


According to (link 8), I need to add the following to package.json:

- "homepage": "."

That alone doesn't solve the problem.  Another answer in the same thread suggests using "HashRouter" instead of "BrowserRouter" for react-router.  So I modified App.js accordingly, changing all occurrences of BrowserRouter to HashRouter in src/App.js.  I reran the build and again tried to run the server:

- npm run build
- serve -s build

This still doesn't work, the page is still blank.  Hmmmmmmm.  If I "git stash" all the changes made in the web app directory today and run the app using npm start, the application runs correctly.

(Link 8) gives some ideas for troubleshooting a blank web application page after building and static deployment, including checking the browser console.  I opened the browser console and see this:

Uncaught Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ./src/domain/Constants.js
    at Object.set [as exports] (harmony module decorator:7:1)
    at ./src/domain/Constants.js (Constants.js:16:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/domain/filter/QueryFilter.js (QueryFilter.js:4:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/pages/SnapshotListPage/SnapshotListPage.js (QueryResultsPanel.js:4:1)

So it sounds like there are more issues with my import/export syntax.  I'm going to edit the places I assign module.exports to see if that solves the problem:

- src/domain/Constants.js
- src/domain/filter/QueryFilter.js
- src/domain/grpc-client/DatastoreApi.js

That solves the problem!  Now I'm going to back out a couple of the changes that I made trying to solve this, adding "homepage" to package.json, and using HashRouter instead of BrowserRouter in App.js.  I made those changes and now to rebuild and run dev server:

- npm run build
- npm start

That works, so those changes were not necessary, apparently.  There are now no errors in the browser console.  So I'm going to try to use "serve" to run the application instead of "npm start":

- serve -s build

This gives the same error, about module.exports, but in a different file.  I'm going to search for all assignments of module.exports:

- domain/filter/AnnotationFilterCriteria.js
- domain/filter/AttributeFilterCriteria.js
- domain/filter/FilterCriteriaBase.js
- domain/filter/PvFilterCriteria.js
- domain/filter/TimeRangeFilterCriteria.js
- domain/grpc-client/grpc-proto/query_grpc_web_pb.js
- domain/models/Annotation.js
- domain/models/Pv.js
- domain/models/Snapshot.js
- domain/models/SnapshotDataPageModel.js
- domain/models/SnapshotDataPageQueryParams.js
- domain/models/SnapshotDataRowModel.js

I edited these files to remove all uses of module.exports.  In all cases but the protoc generated file (query_grpc_web_ps), I added "export default" to the class declaration.

So it's not as easy as removing the module.exports assignments, as that breaks the corresponding imports of those classes.  So I think I need to change the import syntax accordingly.  I now get errors on the imports for those classes, so I need to change the import syntax from "const FilterCriteriaBase = require("./FilterCriteriaBase");" to "import FilterCriteriaBase from "./FilterCriteriaBase";" for default imports, and from "const {QueryServiceClient} = require("./grpc-proto/query_grpc_web_pb");" to "import {QueryServiceClient} from "./grpc-proto/query_grpc_web_pb";" for non-default imports.

OK now this is getting messy.  Those changes were ok because they are classes I control.  But now there are issues with the exports from the protoc-generated grpc classes, e.g., QueryServiceClient in query_grpc_web_pb.js.  I reverted that file back to using module.exports = proto.  With these changes, things seem to work!

- npm run build
- npm start
test using webpack dev server, no issues
- serve -s build
test using static deployment via serve, no issues

Now I need to commit these changes, pull them back into Webstorm, and see what it has to say about them!

### Links

1. creating production build https://create-react-app.dev/docs/production-build 
2. deploying react app via static server https://create-react-app.dev/docs/deployment/#static-server 
3. "serve" page on github https://github.com/vercel/serve 
4. javascript exports https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export 
5. javascript module exports vs. export default https://bignerdranch.com/blog/default-exports-or-named-exports-why-not-both/ 
6. ES6 modules and how to import/export https://www.digitalocean.com/community/tutorials/js-modules-es6 
7. finding global node modules in search path https://stackoverflow.com/questions/15054388/global-node-modules-not-installing-correctly-command-not-found 
8. web application page is empty after static deployment with create-react-app https://medium.com/@siddhantahire98/how-to-fix-the-blank-screen-after-a-static-deployment-with-create-react-app-2e76983a5d5d

**Comment by craigmcchesney** [comment]
I resolved some issues due to a mixture of ES6 and CommonJS style export/import statements in the web application when using create-react-app's build script (see below for details).  In a nutshell, for each of my domain class files I did the following:

- removed assignment of module.exports
- added "export default" to the class declarations
- use "import" instead of "require" where these files are utilized

Having done that, I was then able to build the application using "npm run build" and then deploy the application using both the webpack development server (via "npm start") and the static "serve" file server (via "serve -s build").

Before I go to the next step, which is to build a simple node server to deploy the static build of the application, I want to update the datastore-web-app directory on my development VM, and see if the Webstorm IDE that I'm using there encounters any problems with the changes.

One question that I have is why "npm run build" updates the package-lock.json and package.json files.  The former had a significant amount of changes in the process, over 15K lines added and removed.  I want to investigate that a bit first before I look at Webstorm.

According to ([Link 1](https://www.freecodecamp.org/news/javascript-package-manager-npm-and-yarn/)), the package-lock.json file is used to describe the exact versions of packages comprising the program's dependency tree so that it can be recreated by other users.  The package.json file specifies constraints on the versions, but the package-lock.json file specifies exact versions.  According to ([Link 2](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json)), the package-lock.json file is intended to be committed into the source repository.  Given that, it doesn't seem like the changes to these files should cause problems for webstorm.

The application appears to run without any problems, so I'm going to close the associated github issue.
### Links
1. npm package manager and package.json, package-lock.json files https://www.freecodecamp.org/news/javascript-package-manager-npm-and-yarn/ 
2. package-lock.json documentation on npmjs.com https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json
